config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

resources :users, only: [:new, :create]
resources :sessions, only: [:new, :create] do
  delete :destroy, on: :collection
end

resources :ideas do
  resources :comments
  resources :likes, only: [:create, :destroy]
  resources :memberships, only: [:create, :destroy]

end

root "ideas#index"

end

app/models/idea.rb
class Idea < ApplicationRecord

  mount_uploader :image, ImageUploader
  
  belongs_to :user
  has_many :comments, dependent: :destroy

  has_many :likes, dependent: :destroy
  has_many :users, through: :like

  has_many :memberships, dependent: :destroy
  has_many :users, through: :memberships

  def like_for(user)
      likes.find_by_user_id(user)
  end
 def membership_for(user)
   memberships.find_by_user_id(user)
 end

end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
before_action :find_idea, only: [:show, :edit, :destory, :update]
before_action :authenticate_user!, except: [:index, :show]
  def index
    @ideas = Idea.all.order(created_at: :desc )
    # @user= User.new
    # @idea = Idea
    # @like =  @ideas.like_for(current_user)

  end

  def edit
    redirect_to root_path, alert: "access defined" unless can? :edit, @ideas
  end

  def show
    @idea = Idea.find params[:id]
    @user = @idea.user

    @comment = Comment.new
    @comments = Comment.all

  end

  def new
    @ideas = Idea.new
  end

  def create
       @ideas= Idea.new find_params
       @ideas.user = current_user
      if @ideas.save
        # @ideas.avatars[0].url # => '/url/to/file.png'
        #   @ideas.avatars[0].current_path # => 'path/to/file.png'
        #   @ideas.avatars[0].identifier #
        redirect_to ideas_path, notice: "ideas published successfully"
      else
        flash[:alert] = "ooops"
        render :new
      end

  end

  def update
    redirect_to root_path, alert: "access defined" unless can? :update, @ideas
    if @ideas.update find_params
      redirect_to idea_path(@ideas), notice: " updated"
    else
      flash[:alert] = "ooopppppsss"
      render :edit
    end
  end

  def destroy
    @ideas = Idea.find params[:id]
    redirect_to root_path, alert: "access defined" unless can? :destroy, @ideas
    @ideas.destroy
    redirect_to root_path, notice: " Idea deleted"

  end
  private

  def find_idea
   @ideas = Idea.find params[:id]
  end
  def find_params
    params.require(:idea).permit([:title, :body, :user_id, :image])
  end


  end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/views/ideas/_form.html.erb
<%= simple_form_for @ideas do |ide| %>
<div>
<%= ide.input :title %>
</div>
<div>
<%= ide.input :body %>
<%= ide.input :image %>

</div>
<%= ide.submit class:"btn btn-danger" %>
<% end %>

app/views/ideas/edit.html.erb
<%= render "form" %>

app/views/ideas/index.html.erb
<% @ideas.each do |ide| %>

<h2><%= link_to ide.title, idea_path(ide) %></h2>
<br>
<div class="left">
<%= raw(ide.body) %>
</div>
<div class="full-name">
by <%= ide.user.full_name %>
</div>
<div class="btn-like">
  <% if can? :like, ide %>
<% if ide.like_for(current_user).present? %>
    <%= button_to "un-like", idea_like_path(ide, ide.likes), method: :delete, class: "btn btn-dd btn-default"%>
  <% else %>
    <%= button_to "Like", idea_likes_path(ide), method: :post, class: "btn btn-dd btn-default" %>
  <% end %>
  <% else %>
  like
  <% end %>
  <% if can? :membership, ide %>
  <% if ide.membership_for(current_user).present? %>
  <%= button_to "Leave", idea_membership_path(ide, ide.memberships), method: :delete, class: "btn btn-dd btn-default"   %>
  <% else %>
  <%= button_to "Join", idea_memberships_path(ide), method: :post, class: "btn btn-dd btn-default"%>
  <% end %>
<%   else  %>
membership
<% end %>
</div>
<div class="likes">
  (<%= pluralize ide.likes.count, "like" %>)
  |
  (<%= pluralize ide.memberships.count, "member" %>)
<div>
  <br>
<hr>



<% end %>

app/views/ideas/new.html.erb
<%= render "form" %>

app/views/ideas/show.html.erb
<div class="row">
<div class="col-sm-8 blog-main">
    <div class="blog-post">
      <h2 class="blog-post-title"><%= @ideas.title %></h2>
        <p class="blog-post-meta"><%= @ideas.created_at %><a href="#"><%= @idea.user.id %></a></p>
    </div>

<p><%= @idea.body %></p>
<%  if @idea.image.present? %>
    <%= image_tag @idea.image.url(:large) %>
    <% end %>
</div>
  <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
    <div class="sidebar-module sidebar-module-inset">

      <% if can? :edit, @ideas %>
      <%= link_to "Edit", edit_idea_path(@ideas) %>
      <% end %>
      <% if can? :destroy, @ideas %>
        <%= link_to "Delete", idea_path(@ideas), method: :delete, data: {confirm: "Are you sure?"} %>
      <% end %>
        (<%= pluralize @ideas.likes.count, "like" %>)
        (<%= pluralize @ideas.memberships.count, "Memeber" %>)
        <% @ideas.memberships.each do |memebrship| %>
        <p> Name of Member: <%= memebrship.user.first_name %></p>
        <% end %>
      </div>
    </div>
  </div>
<hr>
<div>
<% @ideas.comments.each do |comm| %>

<p><%= comm.body %></p>
<% end %>

<%= form_for [@ideas, @comment] do |comment| %>
<div class="form-group">
<%= comment.label :body %>
<%= comment.text_area :body, class: "form-control" %>
<%= comment.submit %>
<% end %>
<div>