config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

resources :users, only: [:new, :create]
resources :sessions, only: [:new, :create] do
  delete :destroy, on: :collection
end

resources :ideas do
  resources :comments
  resources :likes, only: [:create, :destroy]
  resources :memberships, only: [:create, :destroy]

end

root "ideas#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Quiz3</title>
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>
      <div class="blog-masthead">
            <div class="container">
              <nav class="blog-nav">
                <!-- <a class="blog-nav-item active" href="#">Home</a> -->
                <%= link_to("Home", root_path, {class: "blog-nav-item active"}) %>

                <% if user_signed_in? %>
                  Hello <%= current_user.full_name%>
                  <%= link_to "Logout", sessions_path, method: :delete, class: "blog-nav-item nav-item3",
                             data: {confirm: "are you sure you want to log out?"}%>
                <% else %>
                  <%= link_to "Login", new_session_path, class: "blog-nav-item nav-item3" %> |
                  <%= link_to "Sign Up", new_user_path, class: "blog-nav-item nav-item3" %>
                <% end %>
                <%= link_to "New", new_idea_path, method: :get, class: "blog-nav-item nav-item3" %>

              </nav>
            </div>
          </div>



          <div class="container">

                <div class="blog-header">
                  <img src="https://upload.wikimedia.org/wikipedia/en/thumb/c/cf/Idea_Cellular_Logo.svg/320px-Idea_Cellular_Logo.svg.png" width=150px>
                  <h1 class="blog-title">Idea Creator</h1>

                </div>



        <%= yield %>

</div>

    </body>
</html>